SECTOR_COLUMNS = {
    "financial_services": ["Transaction Date", "Transaction Amount", "Country", "Client ID",
                           "Transaction Type", "Transaction Count", "Profit",
                           "Credit Rating", "Time", "Transaction Details"],
    "marketing_ecommerce": ["Purchase Date", "Purchase Amount", "Country", "Buyer ID",
                            "Product Category", "Product Count", "Sales Profit",
                            "Buyer Rating", "Purchase Time", "Product Details"],
    "education": ["Registration Date", "Course Fee", "Country", "Student ID",
                  "Course Type", "Course Duration", "Course Completion Rate",
                  "Student Rating", "Time", "Course Details"],
    "healthcare": ["Examination Date", "Procedure Cost", "Country", "Patient ID",
                   "Procedure Type", "Procedure Count", "Medical Expenses",
                   "Health Score", "Time", "Procedure Details"],
    "hr_recruitment": ["Hire Date", "Salary", "Country", "Employee ID",
                       "Employee Role", "Employee Count", "Retention Rate",
                       "Performance Rating", "Time", "Employment Details"],
    "logistics": ["Delivery Date", "Delivery Cost", "Country", "Order ID",
                  "Cargo Type", "Unit Count", "Logistics Expenses",
                  "Delivery Efficiency", "Time", "Cargo Description"],
    "retail": ["Sale Date", "Sale Amount", "Country", "Customer ID",
               "Product Category", "Product Count", "Profit Margin",
               "Product Rating", "Sale Time", "Product Description"],
    "investment": ["Transaction Date", "Investment Amount", "Country", "Investor ID",
                   "Asset Type", "Share Count", "ROI",
                   "Investment Rating", "Time", "Investment Details"],
    "real_estate": ["Purchase Date", "Property Value", "Country", "Property ID",
                    "Property Type", "Unit Count", "Revenue",
                    "Property Rating", "Time", "Property Details"],
    "tourism": ["Booking Date", "Package Cost", "Country", "Client ID",
                "Package Type", "Guest Count", "Tour Revenue",
                "Client Satisfaction", "Booking Time", "Package Details"]
}
